### PR TITLE
Patch v1.0.1

### PR DESCRIPTION
**Pull request by PaoloP74**
Add Wire and Wire1 library
Add SPI and SPI1 library
Modified board.txt
Moved and modified pins_arduino.h
Add credit to readme

### CODE REVIEW

**Comment by Testato** [comment]
+1

**Comment by awatterott** [comment]
Thanks.
PS: I am working on a BSP with the Atmel Toolchain.

**Comment by Testato** [comment]
Why an BSP ?

it is better a standard .json file, officially supported by Arduino IDE via Board Manager.
It will work on all OS and will be published on the Arduino core list
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

**Comment by awatterott** [comment]
I mean with BSP a json file, which can be installed via the boards manager.

**Pull request merged**
