### PR TITLE
AvrDude 6.3

### PR DESCRIPTION
**Pull request by PaoloP74**
Atmega328pb need new Avrdude to upload sketch.
The zip file contains avrdude.exe and avrdude.conf in the tools subdir.
The modified path, in platform.txt file, is needed for use avrdude 6.3 instead of standard avrdude.

Note: I also added avrdude.exe files to bin subdir, but github does not allow to load it.

### CODE REVIEW

**Comment by awatterott** [comment]
Yes, I know and I will add it as a separate tool like the compiler. Otherwise it will only work on Windows operating systems.

**Comment by PaoloP74** [comment]
:+1:

**Comment by awatterott** [comment]
I have added avrdude 6.3. There are some issues with path variables, so it took a lot of testing.

**Comment by PaoloP74** [comment]
--> CRC doesn't match. File is corrupted.

**Comment by PaoloP74** [comment]
--> CRC doesn't match. File is corrupted.

**Comment by awatterott** [comment]
I have not changed the version number. So you have to clean the staging directory `\Users\Local\Arduino15\staging\packages\`, because the IDE does not download existing files.

**Comment by PaoloP74** [comment]
I use a separate and portable version to test it.
MD5 doesn't match.
In the json file: cc1247bb96537bae7caf5985020657f4
My calc: ec665463025eaafb940e0a3e9ef1fee5

**Comment by awatterott** [comment]
Yes, I have not uploaded the correct version. It is now corrected.

**Pull request closed without merging**
